update file html and css
st-baonguyen2/FE-Internship-Summer-2022_st-baonguyen2_FE-Exercise pull request #5
Opened 2022-06-12 05:35 UTC by st-baonguyen2

#### References
- Related PR URL(https://www.figma.com/file/CUQiZbPKOlfjHZn9hBqrPh/Fashion?node-id=8%3A194)
#### Description
![image](https://user-images.githubusercontent.com/106952062/173217217-b5153334-ab02-4b9e-95db-af06fb8c5c13.png)
-added file html,css,img

2022-06-12 10:40 UTC, st-quangnguyen2 requested changes

2022-06-12 10:40 UTC, st-quangnguyen2 commented on Exercise/style.css
> +}
check và fix convention toàn bộ file css
- `.container{` => `.container {`
- indent 2 space

2022-06-13 08:58 UTC, st-quangnguyen2 requested changes

2022-06-13 08:58 UTC, st-quangnguyen2 commented on Exercise/index.html
> +                  </svg>
dùng thẻ `i` cho `icon`, không dùng thẳng `svg` trong file `html`, check lại toàn bộ file

2022-06-13 08:58 UTC, st-quangnguyen2 commented on Exercise/style.css
> +}
add thêm dòng cuối file

2022-06-13 08:58 UTC, st-quangnguyen2 commented on Exercise/style.css
> +a {
check lại convention, anh thấy vẫn còn space 4 ở nhiều chỗ, chỉnh hết lại thành space 2.

2022-06-13 08:58 UTC, st-quangnguyen2 commented on Exercise/style.css
> +    /* background: linear-gradient(90deg, #000000 33.28%, rgba(0, 0, 0, 0) 94.05%); */
css không sử dụng thì xoá luôn

2022-06-13 17:33 UTC, st-duynguyen commented on Exercise/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap');
Format lại thành 2 space

2022-06-13 17:33 UTC, st-duynguyen commented on Exercise/style.css
> +html, body, div, span, applet, object, iframe,
Đoạn này e cop ở đâu mà nhiều dữ ri

2022-06-13 17:35 UTC, st-duynguyen commented on Exercise/style.css
> +    width: 166px;
Không set cứng width height cho btn, nhất là class btn dùng chung

2022-06-13 17:37 UTC, st-duynguyen commented on Exercise/style.css
> +    background-color: var(--white);
những thuộc tính chia tiết như background-color, nên khai báo ở những class chi tiết còn đây là class dùng chung, chỉ nên define những thuộc tíh cơ bản nhất của button

2022-06-13 17:38 UTC, st-duynguyen commented on Exercise/style.css
> +
xoá dấu cách k cần thiết

2022-06-13 17:39 UTC, st-duynguyen commented on Exercise/style.css
> +    background-color: red;
ở trên e có khai báo secondary-color sao ở dưới lại k dùng

2022-06-13 17:40 UTC, st-duynguyen commented on Exercise/style.css
> +    display: flex;
E check lại hết tất cả css và nhóm những thuộc tính liên quan lại với nhau. Ex:
```
display: flex;
justify-content: space-between;
align-items: center;
padding-top: 60px;

2022-06-13 17:40 UTC, st-duynguyen commented on Exercise/style.css
> +.menu-item a{
Check lại convention, format lại code cho a

2022-06-13 17:42 UTC, st-duynguyen commented on Exercise/style.css
> +    background-image: linear-gradient(180deg, rgba(0, 0, 0, 0.8) 0%, rgba(0, 0, 0, 0.5)), url(img/Fashion-banner.png);
Dùng shorthand cho thằng này. Ở đây sẽ handle background và after

2022-06-13 17:43 UTC, st-duynguyen commented on Exercise/style.css
> +    display: flex;
Sao ở đâu a cũng thấy e dùng display: flex hết vậy, chỉ dùng cho những trường hợp cần thiết thôi nghe

2022-06-13 17:44 UTC, st-duynguyen commented on Exercise/style.css
> +    display: flex;
A thấy những thằng icon đang có nhiều thuộc tính có thể dùng chung, e có thể tạo thêm 1 class common để dùng chung

2022-06-13 17:44 UTC, st-duynguyen commented on Exercise/style.css
> +    font-size: 14px;
Đối với những loại text hay dùng trong page, e nên đặt thêm 1 class common là text-primary, text-secondary để tiện dùng, k nên đụng tới text nào thì css cho text đó

2022-06-13 17:46 UTC, st-duynguyen commented on Exercise/style.css
> +    width: 143px;
Không bao h set width height cho button cả, handle bằng việc padding

2022-06-13 17:47 UTC, st-duynguyen commented on Exercise/style.css
> +    width: 351px;
Khi css e hạn chết set width height cứng cho từng phần tử như vậy, sau này rất khó để handle responsive

2022-06-13 17:48 UTC, st-duynguyen commented on Exercise/style.css
> +    padding: 13px 24px;
Cái này a nhắc chung: Đa số khi padding e nên nhìn vào tổng thể để padding 1 cục, tức là padding top và bottom nên giống nhau, left và right nên giống nhau, k nên padding mỗi bên mỗi kiểu như vậy, sau này rất khó để debug

2022-06-13 17:48 UTC, st-duynguyen commented on Exercise/style.css
> +.btn-secondary {
Gọp những css cho thằng button lại cùng 1 chỗ

2022-06-13 17:53 UTC, st-duynguyen commented on Exercise/style.css
> +.cost-text {
Check lại font-size. Đang bị sai so với design.

2022-06-13 17:58 UTC, st-duynguyen commented on Exercise/style.css
> +.section-offer {
Check lại tất cả các section có dùng row col, đang chia bị sai so với design

2022-06-13 17:58 UTC, st-duynguyen commented on Exercise/style.css
> +    background-color: #F7F7F7;;
Nên dùng biến color chứ khai báo thẳng như vậy

2022-06-13 18:00 UTC, st-duynguyen requested changes
@st-baonguyen2 Bài của e đang sai nhiều chỗ. Fix những chỗ a nói trc rồi báo a review lại nha

2022-06-14 07:58 UTC, st-duynguyen approved these changes
@st-baonguyen2 A sẽ review kĩ ở PR sass. H a merge để e làm bài tập sass nha.

2022-06-14 07:59 UTC, merged